targets:
  $default:
    builders:
      # Freezed code generation - only for specific model files
      freezed:freezed:
        enabled: true
        generate_for:
          include:
            - lib/models/**/*.dart
            - lib/features/**/*.dart
            - lib/providers/**/*_provider.dart
          exclude:
            - lib/models/training_session/training_exercise.dart
            - lib/models/player.dart
            - lib/models/training.dart
            - lib/models/match.dart
            - lib/models/team.dart

      # JSON serializable - for all models that need JSON support
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/models/**/*.dart
            - lib/features/**/*.dart
          exclude:
            - lib/models/**/*.freezed.dart

      # Riverpod generator - only for provider files
      riverpod_generator|riverpod_generator:
        enabled: true
        generate_for:
          include:
            - lib/providers/**/*_provider.dart

      # Disable Isar generator since we migrated to Hive CE
      isar_generator|isar_generator:
        enabled: false
