name: voab_team_app_workspace
packages:
  - .
  - packages/**

scripts:
  analyze:
    description: Analyze all packages after code generation
    run: |
      melos run gen
      melos exec -c 1 -- "flutter analyze"
  test:
    description: Run tests with coverage (after code generation)
    run: |
      melos run gen
      melos exec -c 1 -- "flutter test --coverage"
  fix:
    description: Apply Dart fixes & format across the workspace
    run: |
      melos exec -c 1 -- "dart fix --apply"
      melos exec -c 1 -- "dart format ."
  analyze_strict:
    description: Analyze with --fatal-infos to enforce clean code
    run: melos exec -c 1 -- "flutter analyze --fatal-infos"
  gen:
    description: Generate code for all packages (build_runner)
    run: |
      melos exec -c 6 -- "flutter pub run build_runner build --delete-conflicting-outputs"
