# Netlify Configuration - 2025 Best Practices
[build]
  # Skip build - using pre-built artifacts from GitHub Actions
  # Modern 2025 pattern: Build in CI, Deploy artifacts
  publish = "build/web"

[build.environment]
  # Current stable versions (aligned with GitHub Actions)
  FLUTTER_VERSION = "3.32.x"
  NODE_VERSION = "20"
  DART_SDK_VERSION = "3.2.x"

  # Flutter Web optimizations
  FLUTTER_WEB_USE_SKIA = "true"
  FLUTTER_WEB_CANVASKIT_URL = "https://unpkg.com/canvaskit-wasm@0.39.1/"

  # App environment - Multi-environment support (2025)
  DART_DEFINE_APP_ENV = "production" # Secrets (e.g. SUPABASE_URL/ANON_KEY) are managed via Netlify Environment Variables

  # Build optimizations
  FLUTTER_BUILD_MODE = "release"
  ENABLE_FLUTTER_DESKTOP = "false"

# Modern build processing with 2025 optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# 2025 Complete Security Headers - Production Ready
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy v3 - 2025 Enhanced
    Content-Security-Policy = """
      default-src 'self' https://ohdbsujaetmrztseqana.supabase.co;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com https://unpkg.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      media-src 'self' https: blob:;
      connect-src 'self' https://ohdbsujaetmrztseqana.supabase.co https://*.supabase.co wss://realtime.supabase.co wss://*.supabase.co https://www.gstatic.com https://fonts.gstatic.com https://*.sentry.io https://ingest.sentry.io https://*.ingest.sentry.io;
      worker-src 'self' blob:;
      frame-src 'none';
      frame-ancestors 'none';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
      require-trusted-types-for 'script';
      trusted-types dompurify;
    """

    # Frame Protection - 2025 Enhanced
    X-Frame-Options = "DENY"

    # Content Type Protection
    X-Content-Type-Options = "nosniff"

    # Referrer Policy - Privacy Enhanced
    Referrer-Policy = "strict-origin-when-cross-origin"

    # XSS Protection
    X-XSS-Protection = "1; mode=block"

    # HSTS - Extended Protection
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

    # 2025 NEW: Permissions Policy (Feature Policy v2)
    Permissions-Policy = """
      camera=(),
      microphone=(),
      geolocation=(self),
      payment=(),
      usb=(),
      bluetooth=(),
      accelerometer=(),
      gyroscope=(),
      magnetometer=(),
      ambient-light-sensor=(),
      encrypted-media=(self),
      autoplay=(self),
      picture-in-picture=(self),
      fullscreen=(self),
      interest-cohort=()
    """

    # Cross-Origin Policies - 2025 Standards
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"

    # Security Headers for APIs
    X-Permitted-Cross-Domain-Policies = "none"

    # Cache Control for Security
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# API specific headers - Extra Secure
[[headers]]
  for = "/api/*"
  [headers.values]
    # API-specific CSP
    Content-Security-Policy = "default-src 'none'; frame-ancestors 'none';"
    Content-Type = "application/json; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# HTML files - no cache for dynamic content
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Vary = "Accept-Encoding"

# Service Worker - short cache
[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "public, max-age=300"

# Manifest and icons - medium cache
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Static assets caching with security
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Cross-Origin-Resource-Policy = "cross-origin"

# Modern SPA routing with precise rules
[[redirects]]
  from = "/api/*"
  to = "https://your-api-domain.com/api/:splat"
  status = 200
  force = true

# Static assets - prevent SPA redirect
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/*.wasm"
  to = "/:splat.wasm"
  status = 200

[[redirects]]
  from = "/canvaskit/*"
  to = "/canvaskit/:splat"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/flutter_service_worker.js"
  to = "/flutter_service_worker.js"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Context-specific settings for 2025 (using pre-built artifacts)
[context.production]
  publish = "build/web"

[context.deploy-preview]
  publish = "build/web"

[context.branch-deploy]
  publish = "build/web"

# Modern Edge Functions (2025)
[functions]
  directory = "netlify/edge-functions"
  node_bundler = "esbuild"

# Performance optimizations
[build.processing.images]
  compress = true

# Modern form handling
[build.forms]
  spam_filter = true

# Dev server configuration
[dev]
  command = "flutter run -d web-server --web-port=3000"
  port = 8888
  publish = "build/web"
  framework = "#custom"

# Build hooks for 2025 CI/CD (using pre-built artifacts)
[build.hooks]
  # Pre-deployment validation
  before_build = """
    echo "🚀 Deploying pre-built Flutter Web artifacts..."
    echo "📊 Checking build directory:"
    ls -la build/web/ || echo "No build directory found - will be uploaded by CI"
  """

  # Post-deployment validation
  after_build = """
    echo "✅ Deployment completed successfully"
    echo "📊 Deployed size analysis:"
    du -sh build/web/ || echo "Size analysis not available"
    echo "🔍 Deployed files:"
    ls -la build/web/ || echo "Files listing not available"
  """

# Environment-specific settings
[site]
  id = "your-netlify-site-id"

# Plugin configuration - removed problematic Flutter plugin
# Using native Netlify build process instead
