# Netlify Configuration for JO17 Tactical Manager

[build]
  # Build command for Flutter web
  command = "flutter build web --release --web-renderer canvaskit --tree-shake-icons"

  # Directory to deploy
  publish = "build/web"

  # Node version for build environment
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Flutter SDK version
  FLUTTER_VERSION = "3.29.0"

  # Dart SDK version (included with Flutter)
  DART_VERSION = "3.6.0"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent clickjacking
    X-Frame-Options = "DENY"

    # Enable XSS protection
    X-XSS-Protection = "1; mode=block"

    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"

    # Referrer policy
    Referrer-Policy = "strict-origin-when-cross-origin"

    # Content Security Policy
    Content-Security-Policy = "default-src 'self' https://*.supabase.co; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.supabase.co; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://*.supabase.co blob:; font-src 'self' data:; connect-src 'self' https://*.supabase.co wss://*.supabase.co;"

# Cache Control for Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Deploy Context Settings
[context.production]
  environment = { FLUTTER_BUILD_MODE = "release" }

[context.deploy-preview]
  environment = { FLUTTER_BUILD_MODE = "profile" }

[context.branch-deploy]
  environment = { FLUTTER_BUILD_MODE = "profile" }

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs]
    # Performance budget
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9
