name: jo17_tactical_manager
description: A tactical football team management app for JO17 teams
publish_to: 'none'
version: 0.9.0+0

environment:
  sdk: '>=3.5.0 <4.0.0'  # Updated for Dart 3.8.1+ support

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^12.0.0
  graphql_flutter: ^5.1.3
  equatable: ^2.0.5
  collection: ^1.17.2

  # Core UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.0

  # Code generation annotations
  freezed_annotation: ^2.4.4    # Keep stable - major version 3.x may have breaking changes
  json_annotation: ^4.9.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^16.0.0

  # Backend & Database
  supabase_flutter: ^2.5.6
  supabase: ^2.8.0

  # Utilities
  uuid: ^4.5.1
  path_provider: ^2.1.3
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  firebase_performance: ^0.11.0
  intl: ^0.20.2  # For date formatting

  # UI Components
  table_calendar: ^3.1.1
  fl_chart: ^1.0.0

  # Forms & Validation
  flutter_form_builder: ^10.1.0
  # form_builder_validators will be added later or we'll use custom validators

  # Export functionality
  pdf: ^3.11.3
  excel: ^4.0.6
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  csv: ^6.0.0
  file_saver: ^0.3.1
  web: ^1.1.1
  flutter_heatmap_calendar: ^1.0.5
  dio: ^5.8.0
  sentry_flutter: ^9.2.0
  opentelemetry: ^0.18.10
  flutter_dotenv: ^5.1.0
  sentry_dio: ^9.2.0
  logger: ^2.0.2

  # Image & file handling
  image_picker: ^1.0.7
  path: ^1.9.0

  # Secure storage for Hive encryption key
  # Prefer stable release; upgrade to 10.x when stable
  flutter_secure_storage: ^9.2.2

  # Local encrypted cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  http: ^1.4.0

  # Video Core Dependencies (Phase 1 Implementation)
  video_player: ^2.8.6
  ffmpeg_kit_flutter: ^6.0.3
  chewie: ^1.7.5  # Enhanced video controls
  wakelock_plus: ^1.2.5  # Prevent screen sleep
  flutter_cache_manager: ^3.3.1

  # Security Implementation (DAG 1 - 2025)
  device_info_plus: ^11.0.0     # Device integrity verification (updated for 2025 compatibility)
  package_info_plus: ^8.3.0     # App signature validation (compatible with wakelock_plus)

  # Analytics & Data (duplicates removed)
  riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.2
  test_utils:
    path: packages/test_utils
  mocktail: ^1.0.1
  mockito: ^5.4.4
  coverage: ^1.7.2
  # Replaced by very_good_analysis for stricter lint set
  very_good_analysis: ^9.0.0

  # Modern Testing Tools (2025 UI Automation Plan)
  # Note: Using stable, well-supported testing dependencies
  flutter_driver:
    sdk: flutter

  # Visual regression testing
  golden_toolkit: ^0.15.0

  # Network testing
  http_mock_adapter: ^0.6.1

  # Database testing
  sqflite_common_ffi: ^2.3.3

  # Custom lint removed - conflicts with analyzer 6.11.0 (AugmentationImportDirective missing)
  # Using very_good_analysis instead for comprehensive linting

  import_sorter: ^4.6.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.1  # Re-enabled with Phase 1 solution
  shared_preferences: ^2.2.2

  # Code generation
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # New dev dependency
  hive_test: ^1.0.1
  leak_tracker: ^10.0.7

  crypto: any
flutter:
  uses-material-design: true

dependency_overrides:
  # Updated for Dart 3.8.1+ and Flutter 3.32.x compatibility (2025)
  analyzer: ^7.0.0                    # Support for AugmentationImportDirective
  analyzer_plugin: ^0.13.2           # Fix publiclyExporting issue
  custom_lint_core: ^0.6.7           # Latest stable for Dart 3.8.1+
  riverpod_lint: ^2.3.13             # Compatible with riverpod 2.5.1
  meta: ^1.15.0                      # Required by analyzer 7.0.0
  collection: ^1.19.0                # Latest stable version
  pub_semver: ^2.1.5                 # Required by newer analyzer versions
  file: ^7.0.1                       # Keep file version stable
