name: jo17_tactical_manager
description: A tactical football team management app for JO17 teams
publish_to: 'none'
version: 0.9.0+0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^11.5.2
  graphql_flutter: ^5.1.3
  equatable: ^2.0.5
  collection: ^1.17.2

  # Core UI
  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4

  # Code generation annotations
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.2.0

  # Backend & Database
  supabase_flutter: ^2.5.6
  supabase: ^2.8.0

  # Utilities
  uuid: ^3.0.7
  path_provider: ^2.1.3
  firebase_core: ^3.7.4
  firebase_messaging: ^15.2.9
  firebase_performance: ^0.10.1+9
  intl: ^0.19.0  # For date formatting

  # UI Components
  table_calendar: ^3.1.1
  fl_chart: ^0.68.0

  # Forms & Validation
  flutter_form_builder: ^9.3.0
  # form_builder_validators will be added later or we'll use custom validators

  # Export functionality
  pdf: ^3.11.3
  excel: ^4.0.6
  share_plus: ^7.2.2
  file_picker: ^10.1.9
  csv: ^6.0.0
  file_saver: ^0.2.14
  web: ^1.1.1
  flutter_heatmap_calendar: ^1.0.5
  dio: ^5.8.0
  sentry_flutter: ^9.2.0
  opentelemetry: ^0.18.10
  flutter_dotenv: ^5.1.0
  sentry_dio: ^9.2.0
  logger: ^2.0.2

  # Image & file handling
  image_picker: ^1.0.7
  path: ^1.9.0

  # Secure storage for Hive encryption key
  flutter_secure_storage: ^9.0.0

  # Local encrypted cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Networking
  http: ^1.4.0

  # Video Core Dependencies (Phase 1 Implementation)
  video_player: ^2.8.6
  ffmpeg_kit_flutter: ^6.0.3
  chewie: ^1.7.5  # Enhanced video controls
  wakelock_plus: ^1.2.5  # Prevent screen sleep
  flutter_cache_manager: ^3.3.1

  # Analytics & Data (duplicates removed)

  riverpod: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test_utils:
    path: packages/test_utils
  mocktail: ^1.0.1
  coverage: ^1.7.2
  # Replaced by very_good_analysis for stricter lint set
  very_good_analysis: ^7.0.0

  # Phase 2A: Advanced Integration Testing Framework
  patrol: ^3.6.1              # Advanced integration testing
  alchemist: ^0.7.0           # Golden testing for UI regression

  # Custom lint removed - conflicts with analyzer 6.11.0 (AugmentationImportDirective missing)
  # Using very_good_analysis instead for comprehensive linting

  import_sorter: ^4.6.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.6.1  # Re-enabled with Phase 1 solution
  shared_preferences: ^2.2.2

  # Code generation
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  # New dev dependency
  hive_test: ^1.0.1
  leak_tracker: ^10.0.7

flutter:
  uses-material-design: true

dependency_overrides:
  file: 7.0.1
  # Updated for Dart 3.8.1 compatibility - Analyzer version must support AugmentationImportDirective
  analyzer_plugin: ^0.13.1  # Critical fix for publiclyExporting typo
  analyzer: ^7.0.0          # Compatible with Dart 3.8.1 and AugmentationImportDirective
  custom_lint_core: ^0.6.3  # Allow newer versions for Dart 3.8.1 compatibility
