name: test_utils
publish_to: "none"
version: 0.0.1

description: Common test utilities for JO17 Tactical Manager.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.0
  supabase_flutter: ^2.5.6
  jo17_tactical_manager:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  flutter_lints: ^3.0.0
