name: 🚫 DEPRECATED – Legacy CI

on:
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Legacy ci.yml workflow is deprecated and replaced by advanced-deployment.yml"