name: Flutter CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.x'
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Melos bootstrap
        if: ${{ hashFiles('melos.yaml') != '' }}
        run: |
          dart pub global activate melos 2.9.0
          melos bootstrap

      - name: Run tests (with coverage)
        run: flutter test --coverage

      - name: Static analysis
        run: dart analyze

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true
          flags: flutter
          verbose: true

  zap_scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://staging.jo17.app'  # staging url
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -J zap_report.json'