name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: npm ci

      - name: Restore Edge build cache
        uses: actions/cache@v4
        with:
          path: supabase/edge_functions/dist
          key: edge-${{ hashFiles('supabase/edge_functions/**/*.ts', 'package.json') }}

      - name: Build Edge functions (optional)
        continue-on-error: true
        run: |
          if [ ! -d supabase/edge_functions/dist ]; then
            echo "Skipping edge build (supabase-edge-runtime unavailable)";
            npm run build:edge || true
          fi

      - name: Save Edge cache
        uses: actions/cache/save@v4
        if: success()
        with:
          path: supabase/edge_functions/dist
          key: edge-${{ hashFiles('supabase/edge_functions/**/*.ts', 'package.json') }}

      - name: Run unit + e2e tests
        run: npm run test:e2e
