name: docs-snippets

on:
  pull_request:
    paths:
      - 'docs/**.md'
      - 'jo17_tactical_manager/docs/**.md'
      - '**/*.dart'
      - '.github/workflows/docs-snippets.yml'
  push:
    branches: [main]
    paths:
      - 'docs/**.md'
      - 'jo17_tactical_manager/docs/**.md'
      - '**/*.dart'
      - '.github/workflows/docs-snippets.yml'

jobs:
  validate-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install snippets tool
        run: |
          dart pub global activate snippets 0.4.3
      - name: Validate documentation snippets
        shell: bash
        run: |
          if [ -d docs ]; then
            DOC_DIR="docs"
          elif [ -d jo17_tactical_manager/docs ]; then
            DOC_DIR="jo17_tactical_manager/docs"
          else
            echo "No docs directory found, skipping snippet validation."
            exit 0
          fi

          echo "Using documentation directory: $DOC_DIR"
          mkdir -p build/snippets
          snippets --input "$DOC_DIR" --output build/snippets
