name: docs-snippets

on:
  pull_request:
    paths:
      - 'docs/**.md'
      - '**/*.dart'
      - '.github/workflows/docs-snippets.yml'
  push:
    branches: [main]
    paths:
      - 'docs/**.md'
      - '**/*.dart'
      - '.github/workflows/docs-snippets.yml'

jobs:
  validate-snippets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install snippets tool
        run: |
          dart pub global activate snippets 0.4.3
      - name: Validate documentation snippets
        run: |
          snippets --input docs --output build/snippets
