name: Flutter Web CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Flutter Web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug - Show directory structure
      run: |
        echo "=== Current directory ==="
        pwd
        echo "=== Root directory contents ==="
        ls -la
        echo "=== Check if jo17_tactical_manager exists ==="
        if [ -d "jo17_tactical_manager" ]; then
          echo "jo17_tactical_manager directory exists"
          echo "=== Contents of jo17_tactical_manager ==="
          ls -la jo17_tactical_manager/
        else
          echo "jo17_tactical_manager directory NOT found"
          echo "=== Looking for pubspec.yaml ==="
          find . -name "pubspec.yaml" -type f
        fi

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'
        channel: 'stable'

    - name: Install dependencies
      run: |
        # Check if we're already in the Flutter project root
        if [ -f "pubspec.yaml" ]; then
          echo "Found pubspec.yaml in current directory"
          flutter pub get
        elif [ -f "jo17_tactical_manager/pubspec.yaml" ]; then
          echo "Found pubspec.yaml in jo17_tactical_manager"
          cd jo17_tactical_manager
          flutter pub get
        else
          echo "ERROR: Could not find pubspec.yaml"
          exit 1
        fi

    - name: Run tests
      run: |
        if [ -f "pubspec.yaml" ]; then
          flutter test
        else
          cd jo17_tactical_manager
          flutter test
        fi
      continue-on-error: true  # Allow tests to fail for now

    - name: Check code formatting
      run: |
        if [ -f "pubspec.yaml" ]; then
          dart format --output=none --set-exit-if-changed .
        else
          cd jo17_tactical_manager
          dart format --output=none --set-exit-if-changed .
        fi
      continue-on-error: true  # Allow formatting check to fail for now

    - name: Analyze code
      run: |
        if [ -f "pubspec.yaml" ]; then
          flutter analyze --no-fatal-warnings --no-fatal-infos
        else
          cd jo17_tactical_manager
          flutter analyze --no-fatal-warnings --no-fatal-infos
        fi

    - name: Build web
      run: |
        if [ -f "pubspec.yaml" ]; then
          flutter build web --release --web-renderer canvaskit
        else
          cd jo17_tactical_manager
          flutter build web --release --web-renderer canvaskit
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: |
          build/web/
          jo17_tactical_manager/build/web/
        if-no-files-found: warn

  lighthouse:
    name: Lighthouse CI
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: build/web/

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: ./lighthouserc.json
      continue-on-error: true
