name: Flutter Web CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test Flutter Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: jo17_tactical_manager

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
      continue-on-error: true  # Allow tests to fail for now

    - name: Check code formatting
      run: dart format --output=none --set-exit-if-changed .
      continue-on-error: true  # Allow formatting check to fail for now

    - name: Analyze code
      run: flutter analyze --no-fatal-infos

    - name: Build web
      run: flutter build web --release --web-renderer canvaskit

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: jo17_tactical_manager/build/web/

  lighthouse:
    name: Lighthouse CI
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: web-build
        path: jo17_tactical_manager/build/web/

    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        uploadArtifacts: true
        temporaryPublicStorage: true
        configPath: ./jo17_tactical_manager/lighthouserc.json
