name: 🚫 DEPRECATED – Flutter Web CI (replaced by advanced-deployment)

on:
  workflow_dispatch:

jobs:
  notice:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is deprecated. Use advanced-deployment.yml instead."
