name: "🧹 Lefthook Quality Gate"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lefthook:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-flutter
        with:
          flutter-version: 'stable'
          project-path: .
      - name: Install commitlint
        run: npm install --global @commitlint/cli @commitlint/config-conventional
      - name: Run Lefthook hooks
        run: |
          npm install --global lefthook # ensure binary present
          # Lefthook requires at least one file argument in CI
          FILES=$(git ls-files '*.dart' '*.yaml' '*.yml')
          # Build command with repeated --file flags (lefthook >=1.12)
          CMD="npx lefthook run pre-commit"
          for f in $FILES; do
            CMD="$CMD --file $f"
          done
          eval "$CMD"