name: Nightly Quality Assurance

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  full-test-suite:
    name: 🧪 Full Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Format
        run: dart format . --set-exit-if-changed
      - name: Analyze
        run: flutter analyze --fatal-infos
      - name: Run unit/widget tests
        run: flutter test -r expanded
      - name: Upload performance results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: performance-results
          path: performance_results/**

  build-web:
    name: Build Web (CanvasKit + optional Wasm)
    runs-on: ubuntu-latest
    needs: full-test-suite
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --fatal-infos
      - name: Build web (CanvasKit)
        run: flutter build web --release
      - name: Build web (Wasm, allowed-to-fail)
        continue-on-error: true
        run: flutter build web --wasm --release || echo "Wasm build skipped"


